name: Harpoon APK
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
      - uses: digreatbrian/buildozer-action@v2
        with:
          command: buildozer -v android debug
        env: 
            BUILDOZER_LOG_LEVEL: 2
      - uses: actions/upload-artifact@v4
        with:
          name: Harpoon-APK
          path: ./bin/*.apk
